update versions

diff --git a/wsl b/wsl
--- a/wsl
+++ b/wsl
@@ -1,95 +1,123 @@
-U2FsdGVkX1+Ut2MjI/RSA1GYhXKE7XPSV+VfEgbmhM+fQDiN3/mcNXPaRfyhAt/5
-INohBuGybIw+jbm/6KgDFqMbSSGZza/NMUVS6d6T9/v698vkA3NjrID1OzIgMpDs
-KtxN6h1GaXblK1rkUUE708jn95yPtA3AAPtT2+ykdCxCFO7BziLeag1NikR9KjIC
-bn/mGz/QerZSAVfOeYtlFSS5l70PklK1P/DgpYZc5CvOHgD1NAsHo9gjW3DH+PNf
-o7Of7mNyw6gsWRia3DGJjyfghcafUqWlXU4rhEeMy2Hqy6wgFxM7PuGhYdfz/wmg
-ankLKtDrtLK04UgrI9eU9PJiHKlnaRNFIzuTIptdjazgcLIXjaN8zO1uYMGN6Oou
-WOm8z1bQ8ZZIq+gVzpZzqjJ2PP5p3wbKv/43SU+7tUz4+V1D1FdLSUaF1ugMNtkz
-DmYvlWvooXsCdDWy7mTfsNyxuCkAHibuWsx8SmSwmOym2+mSLkWhgpJy8+FaCT6O
-qtCuCGKy3FBJ8n8C6b855HB74Q48hKLsTg52i8HBypVRTS+HxrBqQfZN01o71LZd
-zUnyfSfTzB51JAnpZT2Fn8AaPuoWnRQtimUtZQmCyztxbxVjaObJxpHWW7UVJBMo
-NSDIdGZX1D5aoyyjmMMwV6L0+EcudpTlVxlQOMKvePIqIxOQ6f445SjkWkiTw9aR
-ndon9IyqQDkb1uFT30MhvMdNCp6/XUqNrNLb985w166/es1PufMEbbqXz4+YTsZr
-Qo8ygQs7S3562W1q26QhPp6cs+/aW2Iv4kwfBo3tqmFBjKSx3A5JxvpdbsbzdU3f
-csv+MZuAtAfjcTXE6ifRttQPqvD6uSjJIV9KjkrNYCbuLtllISsSBlvxJJP+ZhJr
-gPXWik3TYSAhOIkS2h618ClmN+xtOQDsZ7R5jTquyje6lZQuU2forURyXUoQbOYr
-iiJR79iTk4GDaOkGzaOW+WahEblIOp/vK9ZTdZ9QQU2flhTq96AehAr49x3q6V/k
-4kxsispWEuBmL5fsjGUxnzB3p7FgePg/R9tWw6SdOfB53pRDxxoYXWT8lZ5Wlo91
-4eNSP96vAMSXJaCr/6l0LypMXMFqJrJUhHLTK2HHy0oD+snWD1vtPx80BKLVo6dY
-6AkDQgI15uR5M3vfKchkCZuoBu6U9T5O/buRHllzJGD1+KUzqq810HOnbbXOuRS9
-G9iil/4J9Q6zkQLQ0oeQLWEXyPLTfvEZ+MsE7jsSdJnSPRyupdBI1bW95WmdlyIw
-c1DIaDJkHXDF2sQpH36PBgLwmnuLdE8Ic1rP2434r9a93k00TqjrBghAZwpjZhoN
-VlxMXnw49oYHzEi4SyIZ/clp1cHVxr+iYtRGQfQP5QFjfaaQ5LxLdxKzgo61sRNJ
-jUKtuW424oBnMf+5b3bI67WopAA5IVtUGPztdp9tu0+Vc5ENazU5v2dT1ytFzhqT
-tBVtENzjEwewcixlX9VnzxDkJ7/OlgdHW6dyA5WCxrqRpctcstP3KuRs1ZUmKyiU
-ipl5gYZh2IaaIVV+U4IWINM3mexlX+hbdlP6EQkizdnAMqgw9i/ZcnMmWwUbbEFN
-WaZdmpOmgVk0Hu/umtzfdD6OMrZPOwp5MFvijMzbAeYevEVsT2bpGCmV/beYUXaf
-XXDqXy93UiOAMHTBcC/B8IWTER9lbx4zt5xMQ/vrDodQ9PrY7MwjrcXXe+SdnM1S
-SiwNUG4aMwsB3JBPiZVupwwrUNzw7X65m0aq9mZ6o8289ex1pbNWij9Q3ClEudRu
-YFHaXVlznHmXxF0UC6bIQG8Ouh+afcdpn/ROPnY0DqQg/rkuMy+zCaJs+EXhH19Y
-f/J2Zv4w5FR7SxHehkG5i3tM0mwrdWW+W1T1LBXhBRTPTlq7IxuZ1wu0c6xbsC92
-M+wwILfKAd2qDwRGx5D+O2BHe8w0qAJL/A6BSGlv1ckJoi7i6BMzlh26flJOJ8do
-bNsRhqcFJlKxx0GTCafpz37u99tDFKw0vIECEyvkMs1CrXr3Dyd7s+S45dqj2eA4
-4ndA2rjJBxcIyLiIQzH1NJ56t9g+NOHNpTUOQgNW2u5VVFye2U6yt1D0UOj/Kzzf
-w4n1+zdROJMLI8Jj0q4R1hknHbxHqAv3o6ecquhirGctT0EFqFlJfSw10xGVhQ5y
-23gHj08kqlPXYbfxl4j6xH4aSkTd7cU7VzB1Vly5QQpN8huzZkxuyGA2xi2GMNVy
-vS/1vRt/orFSoFBluKgz4oLH7IqQJDInSYhSUjfcrlymaklQx7uGGtW9+j/DAKEt
-6GRxo5JxHscPZwVlLIgCWbf3VsMdD0P0usyh3r4qIZzCe2MS5h/59hbjd2w0RNlL
-RgVpImU9dcX5tB0aAiTgebVNOki55KjLPgtS+kCVJb9zx2aQsY7EN2o2pHYZ+XzT
-ScZ7wGFjG/z5r6LJSa7FDN8jlGScAgnZMrc7TrZtRYRvQQJEitwVYlXgWbtO1Ypj
-GIMrlGIQ22wasAveGwip1dZ1+WzGYYJtVVxgNwvvbZakdG8qJtcBoDY9XUy7ibDx
-X0iVYtp1pTos5SAZ8vu+NeEWRdX3A1bNtBB2pVQGWjOe8cRQg6qOn36BA0n+o3mh
-2+YB47aYM8MuH9tdqpA2ExfSgaus/96Y3oog/5WsxFtcJ1RRtrWMwFKyqO3hGNSh
-CsMgcCteV10tsbfKeGbdH8W0v9n5/0A+bLhf3g5QxDOMw9GNYUzz/BWJdo44Taiy
-j90kPhukZbrtD77UY51y7PoMJoFdCcmXLlDihtX429iWplwypPEtIpg12I6CwUIn
-T3nQfOoHB5AAZUKkAMjlkDx47kejwhFarrTL/scgBaRwlNfjUxU98SqRvtoI5xyD
-xxVdVl3GIL4bFS0l1sUmutJ9WOxf3zp8EuBbNcNMkBB40Xd8D75DZOVSE5rt2Inl
-ATxL1oqpxGb8+BLNJzjzjB1rAk8gnhTK+3mrz8Haz1W0z64c9yoWKgfsRDGi0S8o
-hP/OkuN5v3+jWmI+epPTs9i+Bh6mgf3meh0CiucQ6wbXLz7Sss0xx+Sp4dFPOWzz
-OuruHFc9piaWLzFv4zFNO1Z9S2K116A2c3i6sDDn2uz/UTdoZWIR13ShGcsinUOY
-hzxImZR6ZuOmVP1UAcXyB8FGbXSRnUDFDLL60bE0r7gOQU54HicykVxgFYP+rbw6
-M1sw9WFYPcJl49qR6nARH6yytEG4PJItovHKeykp2TWEtLDLKTZvvzwXJhXy9jFi
-j2ung8dJRKfQhRkdGEIsnnrd7/HfWIPCS4qk2pt5dNPDvIDWAqFEPZsL283KYpIg
-YJVQmkQVRBCKGyo6nbF3XAwU7g9iJ01WtUbB/0TtL83OZzmJkTZcn1C2Hby9ywms
-dnebLvHFn4BaQz08puGlvekxwCPP00QxZ0AShD96dz5yTclTJGcexRBZkcyzpaQu
-XqqqYH4qRWcC35UHmfud+EiON+hs5OQGWgfgIaqC2D56QBGY17txXBo+za3NDoyk
-saBA0NhaobnbWO5MRzxtaxaXlAz4ncAck+N5nHXkBJr79XCU+GamwMkajTlRPKPg
-0ueJZhLthSUXJ+6AKFaBeYCarOOuODNCUf9B5NtU/IkyIEJt9XAX/r8Tl192C3iS
-EIpDL5TSfgZoZ36v9SVN2OEBdXbS+TN8rD747kKEQVxsM3ffUeoKu2GaJe8so2hY
-PINR1v+klhHZfPGzDHsa0UQ40BXLGxBj97gz63sZPxXwjOio9aRXj4wFYLQF7jMg
-16jj5hStawVN6UUwxdjH/sOWkmtiIzK+sm3f/hvRPF07OfST6CS0gbfmU6P2gWXP
-EG5qmyEnVB9Q15RT0dF0wtGFNfm0XLCBoBdWAIdSd14UN/DeWscUNiVEeV1xK99h
-81MrOhtC+xqXrPcUKCT4WRVCqwHzc77Iju8vBsvaJ3Au3n89IEA7qIzU0uCsiqZN
-TUaMqkd3YOzNRNz8yJHnG5n8JQsqMP0yVwD4Tc0H87sfupXkU/At9zF3rv2No8DQ
-wwxNTHjz0An8I2UzHRjCE6DjcuAGNHKJmrKb3AzoK3A/OSXXCIdI7RFaoIH9Q/3t
-hDXs+srNcy1teqSZ9PjAz+tHk27tdaR4tfwdVPT4wRVchfkNrq/EVFG/gTDoPNvR
-cRv33HM5BkeVewcBa5ldDBvypoVkTRA0sYwlsDB9DDN3J3vAdkp/P9dVhNK69J0Q
-omr87jv3DhV4mK5tj8qZVw1dqljIY+H4+98e3ezYaDqt+GH5js2M1xkyyYrhpG/x
-KCJ8VzYgNh2T1/azeR2P8yxolYEmdN1+EmMjZJhzG6eKYwJmKQVUXYISVZpRDTNm
-NnluZqjQNDTS87FJhYcLSkzE37+WFXZq7dZYeQH+gBkrk37/Pu44F3hHcoqzZZAG
-IUbvDd3IoGgh6Mhs72auwDTu/K8MyhllaEO5Kw4Rfq0TVwCo0CYra3sth020KeNf
-TNKdbLwQR4qBZIbV/hAs1sGrIp3hj5ENhpbGymCJwVcXJojNtFy4LeoFpDoy+NJJ
-yT/5RTE4d8p/BxO3CjT+tLmkhpO9tOlRHIYPCFQc8H63I2fpHP3scxRV/LcSOJdc
-sOuM8JkisxmL9+FWd8uK1O7K722Hsvfh+HMhw22OoiX/0+f2cM5I0JHrz9SYVjb8
-GCQklOnzFL3slzOe8bDszck7Ba+iSEFAWdErwff763WkdogDd8o7YNQKyNmf2Hrj
-rH7ab96TqkdyMlnLKF/YFbOqq/18LpHY6whsyE034+raTL/rlLW0nLvaXDmhe+DZ
-yG4s/1Nbnv58KES8MLCdNJmBIgRQmqtfXhZuf0xsWBLsSvqCvwAvnCHo0yBIBhts
-qA98n/1qKg9Q4d9AT4v43q1GrY0wVgRfPJNcqj20RF3Qc2UdHsHNcqpfYiyM40NY
-59IUILToT2ngdztvbIhhIeXiiKyDE/mgSIYrEhckznssWLPDriycA7wDQ4nRfKmv
-gP/tV9MPy0p6HBBBN3Qo50cuQMmyEUlGfumzGJ0MFd8Dy6qoS3iy3zuEvWPgqzXj
-tw1D17PBLHnzHS8zWPwrzmfJha8P3CE2gFZi7CYSDt9jmVYaKxHpJ19MIoFj1jOl
-LnCyLQ+sYPz03ZKh70HZqY2HD2JNQ1L5fYNkU9KgK7d0eRt1embgVnWol/8RrmEz
-4aOGSAIUeY3sq0PuCN2kqCSTQcdBuqqVkdIeGcAMz0Y4Kayz7j0ktpns2aq2IA0c
-bGaKd1egbn8JiVZf/KzmGiZh7oJHAMVRSvSKc8TfZN+mwit0rC8ZO+0HaCBPxzzS
-tmIg5+zfoE0uqJ8IVHqIVRnVryy9UME0pR2aJBFFkFDjXTVCDZo2NvMyAAQ2ZCFP
-PhGE2jgOc62IDlLaAmJ/6aZ3p0+RMT4v13B8r74IkAlvtqTXHxKNrd1UIwThbm+d
-mAQrq5L7UbZhdz7kcdtJALTJUAzFpnsGtItIOGV5GrXB3hwHVbUEcJhcRds1xDLt
-0RXJbf7Sk4zVcZxEHfhssjkssKCMPf5G5q8+i+WXKXSKt9fYtJVQw4FTrSEjsY4e
-9YsGwrekEqWdNMoXysAeU2gRHGFykvibjDnV61tJCp4mjvhTP9Dpaeyt6QgmSQz5
-KtWop4I/OUfuO9ANkx6tw9FDljb7AH4qYKxaU1ppLRnM5GrJKFkTdxds4KGBxpUZ
-hDRHQDo2qWvoYvXUAo5QRr+wxK1zxHnKuRuRUcVqzcSlc8j0cy7VWsfCgL1bQbjP
-9mdjUNFnB0Dn+0BUKEYs7ytrxz+5XCy+yclu9D5CrMNtj9mvwdRR0y+T5XP5SBRc
-xQSupMDWkDBR0DCXLmiuzRs4060jDzftinXIYVqd+zJ168asRFVsMO4n5PvyqRNu
-te4JEwKTuLIDfS1yzTHQDpYzIq0hungDyDyyhXbsz6B+I4xKHUzEXO4NmehpKGev
-1hNZx+XXf4yK5qIzbYlJp7HHI5SzNT4uLroN7FUs2IfmRoJhdgqx9FRowAtTnD1C
-o07JvY9Gs3UzVO/x5FF14Q==
+#!/bin/bash
+
+# FileVersion=1
+
+set -euo pipefail
+sudo_file=/etc/sudoers.d/wsl
+
+am_i_wsl(){
+	read version < /proc/version
+	[[ ${version} =~ Microsoft ]]
+}
+
+start_service(){
+	proc="${1}" file="${2}"
+	[[ -f "${file}" ]] || return 0
+	pgrep ${proc} >/dev/null || sudo "${file}" start
+}
+
+check_sudo(){
+	need_setup=0
+	if [[ -f "${sudo_file}" ]]; then
+		read sudo_definition < "${sudo_file}"
+		[[ ${sudo_definition} =~ "${USER} ALL=(ALL) NOPASSWD: ALL" ]] || need_setup=1
+	else
+		need_setup=1
+	fi
+	if [[ ${need_setup} -eq 1 ]]; then
+		echo "User ${USER} does not have NOPASSWD, setting:"
+		sudo "${0}" setup "${USER}"
+	fi
+}
+
+run_vcxsrv(){
+	DISPLAY=${display}
+	if ! xset q >/dev/null 3>&1; then
+		echo "Starting X11 (VcXsrv)"
+		"/mnt/c/Program Files/VcXsrv/vcxsrv.exe" ${display} -noreset -multiwindow -wgl &
+		sleep 3
+		if xset q >/dev/null 3>&1; then
+			echo "X11 (VcXsrv) started."
+		else
+			echo "Error starting X11 (VcXsrv)."
+		fi
+	fi
+}
+
+check_bashrc_local_display(){
+	if [[ -f "${HOME}/.bashrc.local" ]]; then
+		local text
+		readarray -t text < "${HOME}/.bashrc.local"
+		if [[ ${text[$(( ${#text[@]} -1 ))]} != "export DISPLAY=${display}" ]]; then
+			echo "export DISPLAY=${display}" >> "${HOME}/.bashrc.local"
+		fi
+	else
+		echo "export DISPLAY=${display}" >> "${HOME}/.bashrc.local"
+	fi
+}
+
+install_package(){
+	local file="${1}" package="${2}"
+ 	if ! [[ -f "${file}" ]]; then
+ 		echo "Installing ${package}"
+ 		sudo apt-get install -y "${package}"
+ 	fi
+}
+
+create_rxvt_script(){
+	echo "#!/bin/bash" > /usr/local/bin/rxvt
+	echo '. ${HOME}/.bashrc.local' >> /usr/local/bin/rxvt
+	echo "exec nohup /usr/bin/rxvt >/dev/null 2>&1 &" >> /usr/local/bin/rxvt
+	chmod 0755 /usr/local/bin/rxvt
+	exit 0
+}
+
+rxvt-link(){
+	rxvt_lnk="H4sICCPxt1oCA3J4dnQubG5rAIVVe0iTURT/bVlpjZxYK3tphTIp57RmZgjmylYtWy20YpbzEa42Z23NSUFQ/1QkFJHYyyxSCSqICv/InlB/WUgPK8mKiooehEbREzvn+n22zUH3cu6537n3/O455557PjMAxWgluF0XI/J+IRIJNFF92dWgnXNf4bxg7Yq4eV8xQlMgOCYrEMd6CG5zFKMRb3mxrCPhfZZDffJxJKbr9cfikGrMsmFwK0Ca4D5zUq0ahY7KMne1BzmIQgQ+X81e0ryAV3S0I3IYwhzn+L0IhXCgEmVwoxoekmmwRkKtMbdVqGGt8XjLXTPTgdwAXF5j3Icx4XAz3l+CFTWE50U5XJgJUsc4QiZOrvvMqtoElNg9Fbpyf3kgstbFa4z8M5dD2h/W1wPI34qiFCWwE3IFdITtJ2JkYAnRRMkW5imSxmIiNnIIUZ2l+6mahRROKVo22T/bP3OmErQOtqAxOEy2Qe7ZEGpWLIzICqPpCdHUkKmllC2p2ELyzcSdtLeU0Jw0LxHaqST3w0daU5AYdPYK2uumeWJYm6wwYQHM1PlbR1Y4qXMIhgKNicS7pXCNpO/q/Bvj3yqL8lvn686fW17fymvF/aFrXCWFs8q92Wv3OpzyhWx7sH3Wx0OmpfuPTOjUj736qG1Nl2GG/l3MzujI4kqT/+P/1tv7L7lxOL6Sh8nT/JgckkxqZNC4j+7VSJ5Wkodu8sEuknUl9Twh9WId9eCmjVmb/2c7+fiz18o8TpIrAogTM0KSq1QqYHYXYk+MQlZdN25Fx2PX2HrcOAq0t7fD5/Nhrr8Pmtsq2Ds78dZUgItowI+eJvT29uIaORJFvqwmrDSrxfpJf6XLiN0LW753xJ7yrJ+aTfIyPihevDMMurAEaMMmTbJkYK0E/HLPqrw2c6bx8u/YA0n1rrubZCcYOFUAp9AjToGBKF3M0pBJPYOO0WM2Ec9TxBfLDGJXOs0yhUYGdYPQmSXWDAJBTz1tILo7JGOGDytU1Q15ZjxmfzXl0XNLkvzYOKXQ19f/+hShAmWoIEIWQHqwomLxtj5JMDRQhdtpyQJ9T2Lr54Xj1U09yuK9DR/OcF6PkMNBF4LBFQMYQxTNkxwe3mw8znWahSp5lSsVt+TA6PL581BFGegQb7SU+Be6KllplAw5UOq5zkqGNm8o1WYfvBdzqRPXlz0Z17GUD5GRJ3FdClsx/l9rBv4f0kHnNa75Z2urTC2mHN2pbP9exq7gDSairVXKwy1lP3Iv2ovuWArOXgn8sfwFRjHlOs0GAAA="
+	if ! [[ -f "${HOME}/bin/rxvt.lnk" ]]; then
+		echo "${rxvt_lnk}" | base64 -d | gzip -d > "${HOME}/bin/rxvt.lnk"
+	fi
+}
+
+if [[ ${1:-} == "setup" && $# -eq 2 ]]; then
+	echo "${2} ALL=(ALL) NOPASSWD: ALL" >> "${sudo_file}"
+	exit $?
+elif [[ ${1:-} == "rxvt" ]]; then
+	create_rxvt_script
+elif [[ ${#} -eq 1 && ${1} =~ ^:[0-9]+$ ]]; then
+	display=${1}
+else
+	echo "Usage: $(basename ${0}) {display}"
+	echo "Example: $(basename ${0}) :0"
+	exit 0
+fi
+
+if am_i_wsl; then
+	check_sudo
+	install_package /usr/bin/xset x11-xserver-utils
+	install_package /usr/bin/at at
+	install_package /usr/bin/rxvt rxvt-unicode
+	install_package /usr/share/fonts/truetype/inconsolata/Inconsolata.otf fonts-inconsolata
+	install_package /usr/share/doc/xfonts-terminus/README.gz xfonts-terminus
+	install_package /usr/share/doc/xfonts-terminus-oblique/README.gz xfonts-terminus-oblique
+	run_vcxsrv
+	start_service rsyslog /etc/init.d/rsyslog
+	start_service cron /etc/init.d/cron
+	start_service sshd /etc/init.d/ssh
+	start_service atd  /etc/init.d/atd
+	start_service master /etc/init.d/postfix
+	check_bashrc_local_display
+	[[ -f /usr/local/bin/rxvt ]] || sudo "${0}" rxvt
+	rxvt-link
+fi
+
+echo ""
+echo ""
+echo ""
+echo "###############################################################"
+echo "###############################################################"
+echo "###############################################################"
+while true; do
+	read -p"Do not close this terminal while there are remaining terminals."
+	sleep 0.1
+done
